name: CI/CD Django Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Get code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Root Access
        run: |
          sudo -i 
            whoami

      # 2. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Login to ECR
      - name: Login to Amazon ECR
        id: ECR_REGISTRY
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t djanog_webapp-main:latest .

    

      # 6. Push image to ECR
      - name: Push image to ECR
        run: |
          docker push \
          794038243291.dkr.ecr.us-east-1.amazonaws.com/djanog_webapp-main:latest

      # 7. Create SSH key
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/kopix.pem
          chmod 400 ~/.ssh/kopix.pem

      # 8. Deploy to Red Hat EC2
      - name: Deploy to Red Hat EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/kopix.pem \
            ec2-user@${{ secrets.EC2_HOST }} << 'EOF'

            echo "Logging in to ECR..."

            aws ecr get-login-password --region us-east-1 | \
            docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.ECR_REGISTRY }}

            echo "Pulling latest image..."

            docker pull \
            ${{ secrets.ECR_REGISTRY }}/djanog_webapp-main:latest

            echo "Stopping old container..."

            docker stop web2 || true

            echo "Removing old container..."

            docker rm web2 || true

            echo "Starting new container..."

            docker run -d \
              --name web2 \
              -p 3000:8000 \
              ${{ secrets.ECR_REGISTRY }}/djanog_webapp-main:latest

            echo "Deployment completed!"

          EOF
