---
name: CI/CD Django Deployment
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Root Access
        run: |
          sudo -i 
            whoami
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: ECR_REGISTRY
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        run: |
          docker build -t djanog_webapp-main:latest .
      - name: docker tag
        run: >
          docker tag djanog_webapp-main:latest
          794038243291.dkr.ecr.us-east-1.amazonaws.com/djanog_webapp-main:latest
      - name: Push image to ECR
        run: |
          docker push \
          794038243291.dkr.ecr.us-east-1.amazonaws.com/djanog_webapp-main:latest
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/kopix.pem
          chmod 600 ~/.ssh/kopix.pem
      - name: SSH into EC2 and Deploy
        run: >
          ssh -i StrictHostKeyChecking=no \

          -i ~/.ssh/kopix.pem \

          ec2-user@${{ secrets.EC2_HOST }} << 'EOF'


          echo "Logging in to ECR..."

          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}


          echo "Pulling latest image..."

          sudo docker pull ${{ secrets.ECR_REGISTRY }}/djanog_webapp-main:latest


          echo "Stopping old container..."

          sudo docker stop web2 || true


          echo "Removing old container..."

          sudo docker rm web2 || true


          echo "Starting new container..."

          sudo docker run -d -p 80:8000 --name web2 ${{ secrets.ECR_REGISTRY }}/djanog_webapp-main:latest

          EOF
